[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
axum = "0.7.3"
fred = "7.1.0"
futures-util = "0.3.30"
tokio = { version = "1.35.1", features = ["rt", "macros", "net", "fs"] }
